### ISSUE TITLE
full_description.txt in de-DE is en-US

### ISSUE THREAD

**Issue by IzzySoft** [StellarSand/Password-Monitor#1]
Looks like the wrong full description file entered the de-DE directory :wink:

**Comment by StellarSand** [comment]
consequences of wrong copy paste :smile: 
fixed.

**Comment by IzzySoft** [comment]
Thought so, thanks! Should [be live](https://apt.izzysoft.de/packages/com.password.monitor) now :smile: Be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there e.g. from your Readme. Will take a little longer until the F-Droid shield shows something other than "not found" – the shield from IzzyOnDroid should already find it.

**Comment by IzzySoft** [comment]
Btw, I see your app reached F-Droid, congrats! Do you want it to be kept at IzzyOnDroid (where it was already [listed before](https://apt.izzysoft.de/packages/com.password.monitor))? Then you're welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there. If you instead want it to be removed, please let me know.

Btw: as you've established reproducible builds at F-Droid, cross-updates are possible – so there's no conflict but rather an additional distribution channel picking up new releases much faster than F-Droid :wink:

**Comment by StellarSand** [comment]
Hello, apologies for the late response. Yes it would be better to keep it in an additional distribution channel. I already have added a badge in the readme, although it redirects to the F-Droid repo instead of your own, which I'll change. 

I'd also appreciate if you could change the `Author` to `StellarSand`. The current `Potato LLC` that's added there was very likely from the Google Play Store. As stated in the disclaimer under  [Download](https://github.com/StellarSand/Password-Monitor#download) section the Google Play account is not owned by me.

**Comment by IzzySoft** [comment]
Thanks for your response! Updated here according to your wishes: author (yes, that was from the initial metadata import from Play) should be reflected with the next sync around 6 pm UTC, a hint to the "double listing" will be shown then on the repo browser as well. And the app is marked to be kept now.

Speaking of badges: the shields link to their image sources it seems, you might wish having them link to their resp. targets instead as well :wink:

**Comment by StellarSand** [comment]
Thanks a lot!
